trigger:
- master

pool:
  vmImage: Hosted VS2017

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: 2.2.202
- task: PowerShell@2
  inputs:
    targetType: filePath
    filePath: ./build.ps1
