trigger:
- master
- dev
- aspnetcore3
- features/*

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: 3.0.100-preview3-010431
- task: PowerShell@2
  inputs:
    targetType: filePath
    filePath: ./build.ps1
