site_name: IdentityServer4 Documentation
site_description: documentation for identityserver4
site_author: dominick baier and brock allen
copyright: dominick baier and brock allen
site_favicon: favicon.ico
repo_url: https://github.com/identityserver/identityserver4/
page_edit_url: https://github.com/identityserver/identityserver4/docs

pages:
- Home: index.md
- Overview:
    - 'The big Picture': overview/bigPicture.md
    - 'Terminology': overview/terminology.md
    - 'Supported Specifications': overview/specs.md
    - 'Packaging': overview/packaging.md