site_name: IdentityServer4 Documentation
pages:
- Home: index.md
- Overview:
    - 'The big picture': overview/bigPicture.md
    - 'Features': overview/features.md
    - 'Terminology': overview/terminology.md