site_name: IdentityServer4 Documentation
site_description: documentation for identityserver4
site_author: dominick baier and brock allen
copyright: dominick baier and brock allen
site_favicon: favicon.ico
repo_url: https://github.com/identityserver/identityserver4/
edit_uri: blob/dev/docs/

pages:
- Home: index.md
- Overview:
    - 'The big Picture': overview/bigPicture.md
    - 'Terminology': overview/terminology.md
    - 'Supported Specifications': overview/specs.md
    - 'Packaging': overview/packaging.md
- Getting Started:
    - 'Defining Users': gettingstarted/users.md
    - 'Defining Scopes': gettingstarted/scopes.md
    - 'Defining Clients': gettingstarted/clients.md
    - 'Adding IdentityServer to a new Web Application': gettingstarted/newProject.md
    - 'Adding IdentityServer to an ASP.NET Identity Web Application': gettingstarted/aspnetid.md
- Reference:
    - 'Client': reference/client.md
    - 'Scope': reference/scope.md 