site_name: IdentityServer4 Documentation
pages:
- Home: index.md
- repo_url: https://github.com/identityserver/identityserver4/

- Overview:
    - 'The big picture': overview/bigPicture.md
    - 'Features': overview/features.md
    - 'Terminology': overview/terminology.md